import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Image from 'next/image' 
import Navigation from '@/component/Navigation'
import { 
  Flex,
  Box,
  Heading,
  Container,
  Button,
  ButtonGroup
} from "@chakra-ui/react"

export default function Home() {
  return (
    <>
      <Head>
        <title>Kasir Bengkel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation/>
      <Box position="relative" w={"100%"} h="600px">
        <Image
          src="/hero.jpg"
          alt="hero kasir bengkel"
          fill
          style={{objectFit: "cover", transform:"scaleX(-1)"}}
        />
      </Box>
    </>
  )
}
